### ISSUE TITLE
Suggestion:: How to import/require Haxe class in Lua

### ISSUE THREAD

**Issue by darmie** [AndreiRudenko/linc_lua_wrapper#1]
Hi, I am thinking of using this wrapper in a project, however I need to be able to import native classes to Lua using `require()`

**Comment by AndreiRudenko** [comment]
Hey, you can run haxe function from lua, but can't import haxe class.
I do something like this,
create function in Haxe:

``` haxe
LuaWrapper.setFunction("entity_set_pos" 
    function(entName:String, px:Float, py:Float){
        Luxe.scene.get(entName).pos.set_xy(px, py); 
    }
);
```

then call it from Lua:

``` lua
entity_set_pos("player", 3, 7)
```

[link](https://github.com/RudenkoArts/linc_lua_wrapper/blob/master/test/Test.hx#L24)

**Comment by darmie** [comment]
Yeah, thanks.

I also figured that I could do it the traditional Lua way by creating a
metatable for each needed class using the Lua API.
